local parsers = {
    "asm",
    "awk",
    "bash",
    "bitbake",
    "c",
    "caddy",
    "cmake",
    "comment",
    "cpp",
    "css",
    "csv",
    "dart",
    "diff",
    "dockerfile",
    "doxygen",
    "editorconfig",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "glsl",
    "go",
    "gomod",
    "gosum",
    "gpg",
    "html",
    "ini",
    "javascript",
    "jsdoc",
    "json",
    "json5",
    "kitty",
    "lua",
    "make",
    "markdown",
    "proto",
    "python",
    "regex",
    "rust",
    "scss",
    "sql",
    "squirrel",
    "ssh_config",
    "toml",
    "typescript",
    "xml",
    "yaml",
    "yang",
    "zsh",
}

return {
    {
        "nvim-treesitter/nvim-treesitter",
        branch = "main",
        lazy = false,
        build = ":TSUpdate",
    },
    {
        "MeanderingProgrammer/treesitter-modules.nvim",
        dependencies = {
            "nvim-treesitter/nvim-treesitter",
            {
                "nvim-treesitter/nvim-treesitter-context",
                opts = {
                    max_lines = 4,
                    multiline_threshold = 2,
                },
            },
        },
        opts = {
            ensure_installed = parsers,
            fold = { enable = true },
            highlight = { enable = true },
            indent = { enable = true },
            incremental_selection = { enable = true },
        },
    },
}
