source-file ~/.config/tmux/configs/01_base.tmux
source-file ~/.config/tmux/configs/02_keymap.tmux
source-file ~/.config/tmux/configs/03_theme.tmux
source-file ~/.config/tmux/configs/04_vim_tmux_nav.tmux

