# Shortcuts that I often forget
# w, W for panscan
# I for stats screen

# General
player-operation-mode=pseudo-gui
ytdl-format=bestvideo+bestaudio/best
save-position-on-quit=yes

# Decode Opts
vo = gpu-next
profile = high-quality
gpu-api = vulkan
hwdec = auto

# Scaling settings for profile=gpu-hq
scale = ewa_lanczos
cscale = ewa_lanczos
dscale = ewa_robidoux # Polar Catmull-Rom (0.0, 0.5)
dscale-param1 = 0.0
dscale-param2 = 0.5
dscale-antiring = 0.2
correct-downscaling = yes
linear-downscaling = yes
sigmoid-upscaling = yes

# Fiters
deband = yes
interpolation = yes
tscale = catmull_rom
video-sync = display-resample
deinterlace = no
dither-depth = auto
dither = error-diffusion

# HDR
target-trc = pq
target-prim = bt.2020
target-peak = 1000
tone-mapping = spline
hdr-compute-peak = yes
gamut-mapping-mode = perceptual
target-colorspace-hint = yes

# Tweaks/UI
fullscreen
no-osd-bar
osd-font-size = 32
keep-open = yes
volume = 100
volume-max = 100

# Subtitles
alang = eng
slang = eng
sub-auto = fuzzy #Allow loading external subs that do not match file name perfectly.
sub-scale = 0.5

# Screenshot
screenshot-format = png
screenshot-sw = no
screenshot-png-compression = 6 #range 0-9, higher values may lag
screenshot-high-bit-depth = yes
screenshot-tag-colorspace = no
screenshot-directory = "~/picture/mpv"
screenshot-template = '%F_%{estimated-frame-number}'
