addonDir = "/home/pio/extra/SteamLibrary/steamapps/compatdata/306130/pfx/drive_c/users/steamuser/Documents/Elder Scrolls Online/live/AddOns"

[[addons]]
name = "MapPins"
url = "https://www.esoui.com/downloads/download1881"
dependency = false

[[addons]]
name = "QuestMap"
url = "https://www.esoui.com/downloads/download1022"
dependency = false

[[addons]]
name = "LibMapData"
url = "https://www.esoui.com/downloads/download3353"
dependency = false

[[addons]]
name = "LibQuestData"
url = "https://www.esoui.com/downloads/download2625"
dependency = false

[[addons]]
name = "LoreBooks"
url = "https://www.esoui.com/downloads/download288"
dependency = false

[[addons]]
name = "PerfectPixel"
url = "https://www.esoui.com/downloads/download2103"
dependency = false

[[addons]]
name = "LibMapPins-1.0"
url = "https://www.esoui.com/downloads/download563"
dependency = false

[[addons]]
name = "CustomCompassPins"
url = "https://www.esoui.com/downloads/download185"
dependency = false

[[addons]]
name = "LibCustomMenu"
url = "https://www.esoui.com/downloads/download1146"
dependency = false

[[addons]]
name = "JournalQuestLog"
url = "https://www.esoui.com/downloads/download1785"
dependency = false

[[addons]]
name = "LibUespQuestData"
url = "https://www.esoui.com/downloads/download2484"
dependency = false

[[addons]]
name = "AutoCategory"
url = "https://www.esoui.com/downloads/download1798"
dependency = false

[[addons]]
name = "TamrielTradeCentre"
url = "https://www.esoui.com/downloads/download1245"
dependency = false

[[addons]]
name = "CraftStoreFixedAndImproved"
url = "https://www.esoui.com/downloads/download1590"
dependency = false

[[addons]]
name = "LibBinaryEncode"
url = "https://www.esoui.com/downloads/download1647"
dependency = false

[[addons]]
name = "HarvestMap"
url = "https://www.esoui.com/downloads/download57"
dependency = false

[[addons]]
name = "AccountSettings"
url = "https://www.esoui.com/downloads/download3418"
dependency = false

[[addons]]
name = "LibChatMenuButton"
url = "https://www.esoui.com/downloads/download3805"
dependency = false

[[addons]]
name = "BeamMeUp"
url = "https://www.esoui.com/downloads/download2143"
dependency = false

[[addons]]
name = "LibZone"
url = "https://www.esoui.com/downloads/download2171"
dependency = false

[[addons]]
name = "LuiExtended"
url = "https://www.esoui.com/downloads/download818"
dependency = false

[[addons]]
name = "LibMediaProvider-1.0"
url = "https://www.esoui.com/downloads/download56"
dependency = false

[[addons]]
name = "LibMainMenu-2.0"
url = "https://www.esoui.com/downloads/download2118"
dependency = false

[[addons]]
name = "DarkUI"
url = "https://www.esoui.com/downloads/download1576"
dependency = false

[[addons]]
name = "LibAsync"
url = "https://www.esoui.com/downloads/download2125"
dependency = false

[[addons]]
name = "NTakDialog"
url = "https://www.esoui.com/downloads/download2290"
dependency = false

[[addons]]
name = "USPF"
url = "https://www.esoui.com/downloads/download1863"
dependency = false

[[addons]]
name = "DailyProvisioning"
url = "https://www.esoui.com/downloads/download1901"
dependency = false

[[addons]]
name = "PotionMaker"
url = "https://www.esoui.com/downloads/download405"
dependency = false

[[addons]]
name = "WritWorthy"
url = "https://www.esoui.com/downloads/download1605"
dependency = false

[[addons]]
name = "AccurateWorldMap"
url = "https://www.esoui.com/downloads/download3377"
dependency = false

[[addons]]
name = "EndeavorTracker"
url = "https://www.esoui.com/downloads/download3154"
dependency = false

[[addons]]
name = "Azurah"
url = "https://www.esoui.com/downloads/download602"
dependency = false

[[addons]]
name = "CombatAlerts"
url = "https://www.esoui.com/downloads/download1855"
dependency = false

[[addons]]
name = "LibAddonMenu-2.0"
url = "https://www.esoui.com/downloads/download7"
dependency = false

[[addons]]
name = "LibAlchemyStation"
url = "https://www.esoui.com/downloads/download2628"
dependency = false

[[addons]]
name = "LibCharacterKnowledge"
url = "https://www.esoui.com/downloads/download3317"
dependency = false

[[addons]]
name = "LibGPS"
url = "https://www.esoui.com/downloads/download601"
dependency = false

[[addons]]
name = "LibLazyCrafting"
url = "https://www.esoui.com/downloads/download1594"
dependency = false

[[addons]]
name = "LibMapThemer"
url = "https://www.esoui.com/downloads/download3742"
dependency = false

[[addons]]
name = "LibMarify"
url = "https://www.esoui.com/downloads/download2542"
dependency = false

[[addons]]
name = "LibPrice"
url = "https://www.esoui.com/downloads/download2204"
dependency = false

[[addons]]
name = "LibSets"
url = "https://www.esoui.com/downloads/download2241"
dependency = false

[[addons]]
name = "LibTableFunctions-1.0"
url = "https://www.esoui.com/downloads/download2624"
dependency = false

[[addons]]
name = "LibMapPing"
url = "https://www.esoui.com/downloads/download1302"
dependency = false
