set-option -g mouse on
set-option -g set-clipboard on
set-option -g allow-rename off
set-option -s escape-time 0
set-option -g history-limit 50000
set-option -g display-time 4000
set-option -g default-terminal "screen-256color"
set-option -s default-terminal "screen-256color"
set-option -g status-keys emacs
set-option -g focus-events on
set-window-option -g aggressive-resize on
set-option -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
